title: acreciti 
description: a site/blog for things I find interesting
url: "http://acreciti.org"
baseurl: ""

# Build settings
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/

# Collections
collections:
  posts:
    output: true
  projects:
    output: true
    permalink: /projects/:path/
  readings:
    output: true
    permalink: /readings/:path/
  fragments:
    output: true
    permalink: /fragments/:path/
  hall:
    output: true
    permalink: /hall/:path/

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Add this to your existing config
# future: true
