title: acreciti 
description: a site/blog for things I find interesting
url: "http://acreciti.org"
baseurl: ""

# Build settings
markdown: kramdown
permalink: /blog/:title/

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
